### ISSUE TITLE
query报错

### ISSUE THREAD

**Issue by lemon9921010** [open-falcon/query#11]
![image](https://cloud.githubusercontent.com/assets/18395169/20694576/31a30156-b621-11e6-9c3a-dd87a7464869.png)
![image](https://cloud.githubusercontent.com/assets/18395169/20694581/3fade45a-b621-11e6-8eef-57d8528335b9.png)

grafana添加数据源时，query日志报错，哪里出问题了呢，谢谢
@laiwei  @UlricQin

**Comment by laiwei** [comment]
你的query是最新的版本吗？ 另外，query的cfg.json 你仔细检查一遍是否有配错

**Comment by lemon9921010** [comment]
![image](https://cloud.githubusercontent.com/assets/18395169/20737352/171271ca-b6e7-11e6-8468-e88db288c436.png)

昨天又重新编译的，这是配置文件

**Comment by laiwei** [comment]
https://github.com/open-falcon/query/issues/9

看看这个issue，同样的问题，有解决方案。dashboard的url不能是域名。。。

**Comment by lemon9921010** [comment]
**
![image](https://cloud.githubusercontent.com/assets/18395169/20737745/b7ad0e9a-b6e9-11e6-9c2e-84d87fc3b1f1.png)
**
改了，还是报这个错误……

**Comment by laiwei** [comment]
沟通后，发现query的配置文件配置有误，已解决。

**Comment by weichenqi** [comment]
![image](https://cloud.githubusercontent.com/assets/15993498/22143874/9a6ea49a-df36-11e6-960e-4a1f8fffa649.png)
query版本1.4.3的cfg.json的配置如上图，我的理解是http://127.0.0.1:9966/api/grafana/应该有数据返回才是正常的，但是现在返回数据只有[]空，grafana中的测试都是ok的，因为访问是正常的。
![image](https://cloud.githubusercontent.com/assets/15993498/22143963/ee86cc1a-df36-11e6-8ea8-b78f76af6da6.png)
请问问题在哪里，关于grafana的api配置在github上找到两种写法，一种是api和graph同级，一种是api属于graph的子集，求教中。。。 @laiwei
