### ISSUE TITLE
求助query go 报错：graph/graph.go:247: undefined: utils.PK2，utils.KeysOfMap

### ISSUE THREAD

**Issue by zhongyi-peng** [open-falcon/query#2]
[root@openfalcon query]# go get ./...
# github.com/open-falcon/query/graph

graph/graph.go:247: undefined: utils.PK2
graph/graph.go:281: undefined: utils.KeysOfMap
请问缺了哪个组件？

**Comment by niean** [comment]
更新common模块
git pull https://github.com/open-falcon/common.git

**Comment by zhongyi-peng** [comment]
感谢!可以通过了

**Comment by laiwei** [comment]
:+1:
