### ISSUE TITLE
centos7 安装query遇到错误，望回复

### ISSUE THREAD

**Issue by wynelu** [open-falcon/query#6]
[work@iZ236uv37bdZ query]$ ./control start
start ok, pid=12969
[work@iZ236uv37bdZ query]$ ./control tail
2016/04/20 16:04:18 g.ParseConfig ok, file cfg.json
2016/04/20 16:04:18 proc.Start, ok
2016/04/20 16:04:18 graph.Start ok
2016/04/20 16:04:18 http.Start warning, not enabled
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [select (no cases)]:
main.main()
    /home/work/workspace/src/github.com/of-release/query/main.go:40 +0x36d

**Comment by niean** [comment]
程序有点问题。

暂时的办法：http.enabled 设置为 true

**Comment by wynelu** [comment]
确实是这样解决的，赞。

**Comment by MRwangyd** [comment]
![image](https://user-images.githubusercontent.com/27405334/59848603-26655d00-9398-11e9-96e3-df5e88970668.png)
同样问题，帮忙看下配置文件有问题么
