### ISSUE TITLE
grafana调用query api报错

### ISSUE THREAD

**Issue by claybbs** [open-falcon/query#9]
query 版本号：1.4.3 ea558f8
grafana版本号：Version 3.0.4 (commit: v3.0.4)
grafana falcon plugin版本号：1.0.0

错误截图：
![11](https://cloud.githubusercontent.com/assets/7273149/16754552/3e8f0d1a-4826-11e6-8805-3a92240e3c92.jpg)

query配置文件截图：
![11](https://cloud.githubusercontent.com/assets/7273149/16754605/ad455bb0-4826-11e6-94ab-7f42933fc468.jpg)

请告知下我哪个环节配置有问题，非常感谢。

**Comment by laiwei** [comment]
看看query的日志先

**Comment by claybbs** [comment]
@laiwei  query 日志如下:
2016/07/13 16:08:07 Error = Get http://0.0.0.0:8081/api/endpoints?q=&tags&limit=500&_r=0.14633338&regex_query=1: dial tcp 0.0.0.0:8081: connection refused
2016/07/13 16:08:07 http: panic serving 127.0.0.1:56000: runtime error: invalid memory address or nil pointer dereference
goroutine 150 [running]:
net/http.func·011()
	/home/xiaoju/go/src/net/http/server.go:1130 +0xbb
github.com/open-falcon/query/http.getRequest(0x7f665260a828, 0xc20804e3c0, 0xc2080414f0, 0x4f)
	/home/xiaoju/gopath/src/github.com/open-falcon/query/http/api.go:54 +0x512
github.com/open-falcon/query/http.dashboardEndpoints(0x7f665260a828, 0xc20804e3c0, 0xc20807e410)
	/home/xiaoju/gopath/src/github.com/open-falcon/query/http/api.go:63 +0xae
net/http.HandlerFunc.ServeHTTP(0x8c2b80, 0x7f665260a828, 0xc20804e3c0, 0xc20807e410)
	/home/xiaoju/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc20800a8a0, 0x7f665260a828, 0xc20804e3c0, 0xc20807e410)
	/home/xiaoju/go/src/net/http/server.go:1541 +0x17d
net/http.serverHandler.ServeHTTP(0xc2080d8060, 0x7f665260a828, 0xc20804e3c0, 0xc20807e410)
	/home/xiaoju/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc20817c0a0)
	/home/xiaoju/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/home/xiaoju/go/src/net/http/server.go:1751 +0x35e
2016/07/13 16:08:07 http: panic serving 10.252.74.15:56669: runtime error: invalid memory address or nil pointer dereference
goroutine 138 [running]:
net/http.func·011()
	/home/xiaoju/go/src/net/http/server.go:1130 +0xbb
github.com/open-falcon/query/http.getHosts(0x7f665260a828, 0xc20817c000, 0xc208034ea0, 0xc20807449e, 0x0)
	/home/xiaoju/gopath/src/github.com/open-falcon/query/http/grafana.go:70 +0xc0a
github.com/open-falcon/query/http.setQueryEditor(0x7f665260a828, 0xc20817c000, 0xc208034ea0)
	/home/xiaoju/gopath/src/github.com/open-falcon/query/http/grafana.go:183 +0x1f5
github.com/open-falcon/query/http.GrafanaApiParser(0x7f665260a828, 0xc20817c000, 0xc208034ea0)
	/home/xiaoju/gopath/src/github.com/open-falcon/query/http/grafana.go:277 +0x90
net/http.HandlerFunc.ServeHTTP(0x8c2b68, 0x7f665260a828, 0xc20817c000, 0xc208034ea0)
	/home/xiaoju/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc20800a8a0, 0x7f665260a828, 0xc20817c000, 0xc208034ea0)
	/home/xiaoju/go/src/net/http/server.go:1541 +0x17d
net/http.serverHandler.ServeHTTP(0xc2080d8060, 0x7f665260a828, 0xc20817c000, 0xc208034ea0)
	/home/xiaoju/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208140500)
	/home/xiaoju/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/home/xiaoju/go/src/net/http/server.go:1751 +0x35e

**Comment by claybbs** [comment]
@laiwei  找到原因了。"dashboard": "http://10.252.74.15:8081", 这个地方之前配置的是0.0.0.0错了。

**Comment by claybbs** [comment]
@laiwei 感谢

**Comment by jumping** [comment]
我用的是默认配置，grafana也报错“2016/07/27 11:42:41 [I] Completed 192.168.10.17 admin "GET /api/grafana/metrics/find HTTP/1.1" 500 Internal Server Error 0 bytes in 1549us”。在query日志里面没有发现错误提示。

```
{
    "debug": "true",
    "http": {
        "enabled":  true,
        "listen":   "0.0.0.0:9966"
    },
    "graph": {
        "connTimeout": 1000,
        "callTimeout": 5000,
        "maxConns": 32,
        "maxIdle": 32,
        "replicas": 500,
        "cluster": {
            "graph-00": "127.0.0.1:6070"
        }
    },
    "api": {
        "query": "http://127.0.0.1:9966",
        "dashboard": "http://127.0.0.1:8081",
        "max": 500
    }
}
```

**Comment by jumping** [comment]
✋  原来url里面只支持IP，而不支持域名。
![2 pic](https://cloud.githubusercontent.com/assets/255390/17166713/3921dd8a-540b-11e6-903f-dbdce308ee7e.jpg)

**Comment by lemon9921010** [comment]
![image](https://cloud.githubusercontent.com/assets/18395169/20693772/91e9d9be-b61b-11e6-9141-778246ee0d59.png)
grafana添加数据源时，query日志报错，哪里出问题了呢，谢谢
@laiwei @UlricQin
